const HA_REST_URL = "http://supervisor/core/api";
const HA_WS_URL = "ws://supervisor/core/websocket";

const OUTPUT_FILE = "/config/typehass/sdk/generated/mod.ts";

const DEBOUNCE_MS = 2_000;
const RECONNECT_MS = 5_000;

type HaApiState = {
  entity_id: string;
  state: string;
  attributes: Record<string, unknown>;
  last_changed: string;
  last_updated: string;
};

type HaApiServices = Array<{
  domain: string;
  services: Record<string, unknown>;
}>;

type WsMessage =
  | { type: "auth_required" }
  | { type: "auth_ok" }
  | { type: "auth_invalid"; message: string }
  | {
    type: "result";
    id: number;
    success: boolean;
    result?: unknown;
    error?: {
      code: string;
      message: string;
    };
  }
  | {
    type: "event";
    id: number;
    event: {
      event_type: string;
      data: Record<string, unknown>;
      time_fired: string;
    };
  };

function assertToken(): string {
  const token = Deno.env.get("SUPERVISOR_TOKEN");

  if (!token) {
    throw new Error("Missing SUPERVISOR_TOKEN");
  }

  return token;
}

async function ensureOutputDir(): Promise<void> {
  const dir = OUTPUT_FILE.slice(0, OUTPUT_FILE.lastIndexOf("/"));
  await Deno.mkdir(dir, { recursive: true });
}

async function fetchHaJson<T>(
  path: string,
  token: string,
): Promise<T> {
  const response = await fetch(`${HA_REST_URL}${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
  });

  if (!response.ok) {
    throw new Error(
      `HTTP Error ${response.status} for ${path}: ${await response.text()}`,
    );
  }

  return await response.json() as T;
}

function renderConstArray(
  name: string,
  values: readonly string[],
): string {
  return `export const ${name} = [
${values.map((value) => `  ${JSON.stringify(value)},`).join("\n")}
] as const;`;
}

async function generateTypes(reason = "manual"): Promise<void> {
  const token = assertToken();

  console.log(`🦕 Generating HA types. Reason: ${reason}`);

  try {
    const [states, serviceDomains] = await Promise.all([
      fetchHaJson<HaApiState[]>("/states", token),
      fetchHaJson<HaApiServices>("/services", token),
    ]);

    const entityIds = states
      .map((state) => state.entity_id)
      .filter((entityId) => entityId.length > 0)
      .sort((a, b) => a.localeCompare(b));

    const serviceIds = serviceDomains
      .flatMap(({ domain, services }) =>
        Object.keys(services).map((service) => `${domain}.${service}`)
      )
      .filter((serviceId) => serviceId.length > 0)
      .sort((a, b) => a.localeCompare(b));

    const fileContent = `// ----------------------------------------------------
// Auto-generated by deno-ha-typegen.
// Do not edit this file manually.
// ----------------------------------------------------

${renderConstArray("ENTITY_IDS", entityIds)}

export type EntityId = typeof ENTITY_IDS[number];

${renderConstArray("SERVICE_IDS", serviceIds)}

export type ServiceId = typeof SERVICE_IDS[number];

export type HassState<E extends EntityId = EntityId> = {
  entity_id: E;
  state: string;
  attributes: Record<string, unknown>;
  last_changed: string;
  last_updated: string;
};

export type HassEntities = Partial<{
  [E in EntityId]: HassState<E>;
}>;

`;

    await ensureOutputDir();
    await Deno.writeTextFile(OUTPUT_FILE, fileContent);

    console.log(`✅ Generated ${OUTPUT_FILE}`);
    console.log(`✅ Entity count: ${entityIds.length}`);
    console.log(`✅ Service/action count: ${serviceIds.length}`);
  } catch (error) {
    console.error("❌ Failed to generate HA types:", error);
  }
}

let syncTimer: number | undefined;
let syncInFlight = false;
let syncAgain = false;
let lastSyncReason = "manual";

function scheduleTypeSync(reason: string): void {
  lastSyncReason = reason;

  if (syncTimer !== undefined) {
    clearTimeout(syncTimer);
  }

  console.log(`🕒 Scheduling type sync: ${reason}`);

  syncTimer = setTimeout(() => {
    syncTimer = undefined;
    void runTypeSync(lastSyncReason);
  }, DEBOUNCE_MS);
}

async function runTypeSync(reason: string): Promise<void> {
  if (syncInFlight) {
    syncAgain = true;
    lastSyncReason = reason;
    return;
  }

  syncInFlight = true;

  try {
    do {
      syncAgain = false;
      await generateTypes(reason);
      reason = lastSyncReason;
    } while (syncAgain);
  } finally {
    syncInFlight = false;
  }
}

function isNewEntityStateEvent(data: Record<string, unknown>): boolean {
  return data.old_state === null && data.new_state !== null;
}

function isRemovedEntityStateEvent(data: Record<string, unknown>): boolean {
  return data.old_state !== null && data.new_state === null;
}

function startEntityWatcher(): void {
  const token = assertToken();
  const ws = new WebSocket(HA_WS_URL);

  let nextId = 1;
  let shouldReconnect = true;

  ws.onopen = () => {
    console.log("🔌 Connected to Home Assistant WebSocket.");
  };

  ws.onmessage = (message) => {
    let payload: WsMessage;

    try {
      payload = JSON.parse(message.data) as WsMessage;
    } catch (error) {
      console.error("❌ Failed to parse WebSocket message:", error);
      return;
    }

    if (payload.type === "auth_required") {
      ws.send(JSON.stringify({
        type: "auth",
        access_token: token,
      }));
      return;
    }

    if (payload.type === "auth_invalid") {
      shouldReconnect = false;
      console.error(`❌ WebSocket auth failed: ${payload.message}`);
      ws.close();
      return;
    }

    if (payload.type === "auth_ok") {
      ws.send(JSON.stringify({
        id: nextId++,
        type: "subscribe_events",
        event_type: "entity_registry_updated",
      }));

      ws.send(JSON.stringify({
        id: nextId++,
        type: "subscribe_events",
        event_type: "state_changed",
      }));

      ws.send(JSON.stringify({
        id: nextId++,
        type: "subscribe_events",
        event_type: "service_registered",
      }));

      console.log("👂 Watching HA entity and service changes.");
      return;
    }

    if (payload.type === "result") {
      if (!payload.success) {
        console.error(
          `❌ WebSocket subscription failed: ${
            payload.error?.message ?? "unknown error"
          }`,
        );
      }

      return;
    }

    if (payload.type !== "event") {
      return;
    }

    const eventType = payload.event.event_type;

    if (eventType === "service_registered") {
      scheduleTypeSync("service_registered");
      return;
    }

    if (eventType === "entity_registry_updated") {
      scheduleTypeSync("entity_registry_updated");
      return;
    }

    if (eventType === "state_changed") {
      const data = payload.event.data;

      if (isNewEntityStateEvent(data)) {
        scheduleTypeSync("new entity state detected");
        return;
      }

      if (isRemovedEntityStateEvent(data)) {
        scheduleTypeSync("entity state removed");
        return;
      }
    }
  };

  ws.onerror = (error) => {
    console.error("❌ HA WebSocket error:", error);
  };

  ws.onclose = () => {
    console.error("⚠️ HA WebSocket closed.");

    if (!shouldReconnect) {
      return;
    }

    console.error(`Reconnecting in ${RECONNECT_MS}ms.`);
    setTimeout(startEntityWatcher, RECONNECT_MS);
  };
}

export const runTypegenDaemon = async () => {
  await runTypeSync("startup");

  startEntityWatcher();

  Deno.cron("Daily HA Type Sync", "0 3 * * *", () => {
    scheduleTypeSync("daily cron");
  });
};
